# Generated by Django 3.1.2 on 2020-12-30 11:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Week',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=200)),
                ('subject', models.CharField(max_length=200)),
                ('week', models.CharField(max_length=100)),
                ('monday', models.TextField(blank=True)),
                ('tuesday', models.TextField(blank=True)),
                ('wednesday', models.TextField(blank=True)),
                ('thursday', models.TextField(blank=True)),
                ('friday', models.TextField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
