# Generated by Django 3.1.2 on 2020-12-31 18:41

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Week',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(choices=[('Smith', 'Smith'), ('Franz', 'Franz'), ('Jones', 'Jones'), ('Doe', 'Doe')], max_length=200)),
                ('subject', models.CharField(choices=[('Art', 'Art'), ('Business/Computer', 'Business/Computer'), ('English', 'English'), ('F.C. Science', 'F.C. Science'), ('Foreign Language', 'Foreign Language'), ('Math', 'Math'), ('Music/Band', 'Music/Band'), ('Phys Ed./Health', 'Phys Ed./Health'), ('Science', 'Science'), ('Social Studies', 'Social Studies'), ('Special Ed.', 'Special Ed.'), ('Tech Education', 'Tech Education')], max_length=100)),
                ('week', models.CharField(choices=[('01/04/2021', '01/04/2021'), ('01/11/2021', '01/11/2021'), ('01/18/2021', '01/18/2021'), ('01/25/2021', '01/25/2021'), ('02/01/2021', '02/01/2021'), ('02/08/2021', '02/08/2021'), ('02/15/2021', '02/15/2021'), ('02/22/2021', '02/22/2021'), ('03/01/2021', '03/01/2021'), ('03/08/2021', '03/08/2021'), ('03/22/2021', '03/22/2021'), ('03/29/2021', '03/29/2021'), ('04/05/2021', '04/05/2021'), ('04/12/2021', '04/12/2021'), ('04/19/2021', '04/19/2021'), ('04/26/2021', '04/26/2021'), ('05/03/2021', '05/03/2021'), ('05/10/2021', '05/10/2021'), ('05/17/2021', '05/17/2021'), ('05/24/2021', '05/24/2021'), ('05/31/2021', '05/31/2021'), ('06/07/2021', '06/07/2021')], max_length=100)),
                ('monday', ckeditor.fields.RichTextField()),
                ('tuesday', ckeditor.fields.RichTextField()),
                ('wednesday', ckeditor.fields.RichTextField()),
                ('thursday', ckeditor.fields.RichTextField()),
                ('friday', ckeditor.fields.RichTextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
